---
swagger: "2.0"
info:
  description: "The SDC API allows clients to send bulk hit/event data into Analytics"
  version: "1.0"
  title: "Analytics Streaming Data Collection (SDC) API"
host: "analytics-collection.adobe.io"
basePath: "/aa/collect/v1"
tags:
- name: "events"
schemes:
- "https"
paths:
  /events:
    post:
      tags:
      - "events"
      summary: "Upload a batch file to Analytics for processing"
      description: "Uploaded files:   * Must be 100 MB or less compressed (using gzip)\
        \   * Must follow the CSV formatting rules and include the required fields\
        \ as specified in the documentation    "
      operationId: "filePost"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "x-adobe-vgid"
        in: "header"
        description: "Visitor Group ID. A visitor group represents a group of one\
          \ to many report-suites that may be present in a file. The group value is\
          \ a string, and can be whatever value you wish, but it must be consistent\
          \ across files. You could use a comma-delimited list of rsids (i.e. \"rsid1,rsid2,rsid3\"\
          ), or a simple string that represents that group (i.e. \"rsids1-3\" or \"\
          european_report_suites\")."
        required: true
        type: "string"
      - name: "debug"
        in: "query"
        description: "Store debug information for the first 10 hits of the file"
        required: false
        type: "boolean"
        default: false
      - name: "file"
        in: "formData"
        description: "Gzip compressed CSV file sent with request"
        required: true
        type: "file"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UploadedFileInfo"
        400:
          description: "File Error"
          schema:
            $ref: "#/definitions/UploadedFileInfo"
        401:
          description: "Unauthorized Access"
          schema:
            $ref: "#/definitions/ApiError"
  /events/validate:
    post:      
      tags:
      - "events"
      summary: "Upload a batch file to Analytics for validation"
      description: "This file will not be stored on the server or processed into Analytics."
      operationId: "fileValidatePut"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "Gzip compressed CSV file sent with request"
        required: true
        type: "file"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UploadedFileInfo"
        400:
          description: "File Error"
        401:
          description: "Unauthorized Access"
          schema:
            $ref: "#/definitions/ApiError"
definitions:
  ApiError:
    type: "object"
    properties:
      error:
        type: "string"
  ApiSuccess:
    type: "object"
    properties:
      success:
        type: "string"
  FileID:
    type: "object"
    properties:
      file_id:
        type: "string"
  UploadedFileInfo:
    type: "object"
    properties:
      file_id:
        type: "string"
        example: "5c04f400-fca5-420c-9c36-b94aaec55e69"
        description: "The id of the file as a GUID"
      visitor_group_id:
        type: "string"
        example: "myvisitorgroup1"
        description: "The visitor group of the file"
      size:
        type: "integer"
        format: "int64"
        example: 355600
        description: "The size of the compressed file in bytes"
      received_date:
        type: "integer"
        format: "int64"
        example: 1506553535
        description: "The date the file was uploaded in unix epoch time."
      processing_start_date:
        type: "integer"
        format: "int64"
        example: 1506553492
        description: "The date processing was started, in unix epoch time."
      processing_end_date:
        type: "integer"
        format: "int64"
        example: 1506553492
        description: "The date all hits were submitted to analytics, in unix epoch\
          \ time."
      file_reader_complete_date:
        type: "integer"
        format: "int64"
        example: 1506553492
        description: "The date the file was completely read, but the hits weren't\
          \ submitted, in unix epoch time."
      rows:
        type: "integer"
        format: "int64"
        example: 10000
        description: "The number of rows in the file"
      invalid_rows:
        type: "integer"
        format: "int64"
        example: 42
        description: "The number of rows that were not submitted to analytics because\
          \ they were invalid"
      upload_name:
        type: "string"
        example: "myfile1.gz"
        description: "The name the file was uploaded as"
      status:
        type: "string"
        description: "The status of the file"
      status_code:
        type: "string"
        description: "The status of the file as a short name"
        enum:
        - "REJECTED"
        - "UPLOADED"
        - "PROCESSING"
        - "COMPLETE"
        - "ERROR"
      processing_log:
        type: "string"
        description: "A log of errors produced while processing the file"
      error:
        type: "string"
        example: "File not in GZIP format"
        description: "An error message populated on unsuccessful requests"
      success:
        type: "string"
        example: "file is valid"
        description: "A success message populated on validation requests"
